language: scala
os: linux
dist: xenial
scala:
- 2.12.11
- 2.11.11
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.cache/coursier/v1"
  - "$HOME/.sbt"
before_install:
- openssl aes-256-cbc  -md md5 -pass pass:$SONATYPE_PASSWORD -in .travis/secring.gpg.enc
  -out local.secring.gpg -d
- openssl aes-256-cbc  -md md5 -pass pass:$SONATYPE_PASSWORD -in .travis/pubring.gpg.enc
  -out local.pubring.gpg -d
env:
  global:
  - SONATYPE_USERNAME: ashwanthkumar
  - secure: F1rXGIN/TGm4+xC99za+Pnie/T4iM8mN9UZVNUbfbrDvtqmmnXpG7a01TV9YI9sZriM9vn0s+YXlCiASMlQO8Cgft6xTE5lq6kAQV9ZkzqXazDAerwNky9PmfRMCoJqNe6I40xMDf19uSq0VXAHxkua35MjmWqqPsLxr1w371DU6QEDZp+zLcmN5D5pgZGYaSEe9ZYzqRMw84Vvw6xQ5ZNphqzj0jsWGdtdcFgVhWpdcLGkG2L/HNudN/d1nwJG1YpBHWql0uZecgAbt2atVh35KyMZ+uC7xOSaMROjk+Cdci/zzfaUVJ6INkd9UzwZTX4YzzIy9hbJmMMi0QtL3xmyd23hgHRJtMl8nfPdlKRbB6TY698o31cn365cWrTXGeWUKipw+altOnGW6TrjbLbk6hmQEeLqSISw+xjIx1EmXqZSyPvKA3vzPx2PH8FTQQySF1TifyQRI0Iz/vwAqFhH5gQ2882uO6byn1ZBRl/+xUacllpT4kNB1hrrsYm5CKGR5yxgCIO5AbkhsZKnorBSwhbIVwAhVFD3GNatOsLpjTOmcY4q1/94NKdPNb3jxmDzZ2L03NwaU4/f8F8arwcDXnJTLq/9kEsGBSFARF+2f8xynsVOaXCNk0ncUmQpBokrapsF+uC61MxNMg2OooNlh+doD9P2y9XOxMOn7zuw=
  - secure: AZipMA7l1a8kyuO2nXwnGA0ami0kg4RuWG9FbNkQ0EbBlMITiC7KgVQ0TKSuox77f4sioFwWZEQONzwqCtljiy68Ri0qp4WT0ztF7NspKTmN9Ik6Dby/iajC4nVrSJOgjQQJk589WN4GarybOJBDczoSewqbQkNqz4isF1ZXCIC1XUFBCRazKv7muTB2WFYoboHK+C1LwrRcWLTB4fGyXfx131tpTrMER9/10QIXqdir/Gq7cSb4lrGZtNXZRAzo4zbSYKan2vhP3Y3tFq2+FDN1X0nFX/o1L/ZQxyeToIrGettZDdDj9vRnegwlkQjntjX47w5urGaDYvLjiVDSpDCjTBcCszvXiTAzr7j+13shs6XEBI8R7MbrVAKkegk7QsRKzgW6F+s5dYMqjUBx3BD6Jc6tm1V9/aWO4ul5qHXCYId7jugw0QLnieta55YesbzjFcVRrRi4B1mAcF19jNaRg1IwrfxNhevqh68PwvwtuXvhlF565OrnOdvufEGqedLHX77zLL8FZoIFP+0FL3cIMWLk+K+z/pE0Z5S1seKRaV9/O3K6ZMApXPiYdsiFZOKWNzqL/ZdXeU6IBt0dB3qkbaYIResvi/QLnvHOUdO7x8gexQbX4VH2OabvBmACA4qBj7W6pInW6m1EACU2qN/TA6jhsM48Wyl6MFWUH0s=
deploy:
- provider: script
  script: bash .travis/publish.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
    scala: 2.12.11
