language: scala
scala:
- 2.12.11
- 2.11.11
sudo: false
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.cache/coursier/v1"
  - "$HOME/.sbt"
before_install:
- openssl aes-256-cbc  -md md5 -pass pass:$SONATYPE_PASSWORD -in .travis/secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc  -md md5 -pass pass:$SONATYPE_PASSWORD -in .travis/pubring.gpg.enc -out local.pubring.gpg -d
env:
  global:
  - SONATYPE_USERNAME: ashwanthkumar
  - secure: pUedSAl0y9JyitLd8WZYWSPeVK4ipZ6Velb9LnU0zasYeuBZMr1Qz2cP/qbUahpk4t44gkglzMY7UnidpB5nhzyKO+Ag8UXY0/Nym+5XuiI6EiEj4AWEFfaxGI5plJf44fLYABZS/J9toLW0Y9rXK3V++Uh0JsN0CW9kNnhaVvYdnrRR6HSFUOmXpvse0Hh4keFgawJ8M9oGmesBQaifDJsYtynQkFAg3peC9X8t7fqF5Viyzio75udFUz60/l1dfeI1nW7UFLS3T581ZuCyBQaOwXMl709xMdtjZTc/LiqdsKzkWbwVo72piISlMEqi91667ZALV+ixdQ3ZpDBSoafxU+a2W4XVcqKeoQQqnn9vtc3Ah7sXykHKbwwjeSm+AmQyTnYXGMo0MdrMvWwIzD3i5DIeW8N1rZo974WMSRLBnNY+ViHVbjZ9/ko8808y/nu+ccUP2vuT7bARJROs6NCm6zTFtpBgn9CvztKnVlcTbEwc+1ZyRoj8IFVvdvzNE59LHNDMMCGPViNum7l6xC45ytMMyDQ5whscVUj5VnJW4Xj44k4g5uEVMLsipNy+whP7KvkIUe5BbfvvUeMLCsqrSduiY8pL18oxBMxRn8eDXfdZyWepRTxieJCT51I+orELvAF8T/Qc3Su5MHran1b0HvgDAKzJm8n4RhxixQo=
deploy:
- provider: script
  script: "./.travis/publish.sh"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk11
    scala: 2.12.11
